### ISSUE TITLE
change in 

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-virtual#12] opened 2017-08-04 15:42 UTC
As reported in RocketChat on Aug 4, when the service name, host changes, the virtual device does not pick up this change and also change the affected schedule info in Meta Data.  
```
when i boot device-virtual micro service,i got the following error,
and i open a browser and going to localhost:48080/api/v1/event/count,This number has always been 351，the count should not slowly rise by the demo.
ps: i have modify the service.name and service.host in application.properties file.

```

**Comment by trcox** [comment] 2017-08-07 14:18
Solution will have to make sure that a service is able to update its own addressable object when it comes up. Issue is going to be knowing what it was before. May also want to instance scheduleEvents added by a device service to its name for continuity purposes.

Also need to be careful we don't create a situation where a service can overwrite another service's objects unintentionally (which is why the current naive implementation doesn't try to modify the scheduleEvent if it already exists). Also, scheduleEvents need their own Addressable, how do we tie back to the Service Addressable? Do we need addressable inheritance or references?

**Comment by trcox** [comment] 2017-10-23 16:54
Revisiting this, I believe that we have established that the service name is the unique identity of a service. Changing it should detach it from previous history (a.k.a. working as intended).

We need to check up on service host changes and modify initialization behavior to update generated addressables' address to reflect hostname changes.

**Comment by eb-oss** [comment] 2019-02-05 21:19
Closing issue; project is being archived.

**Closed by eb-oss** 2019-02-05 21:19 UTC
